baseurl = "https://megretson.github.io/"
title = "megretson"
theme = "hugo-theme-console"
languageCode = "en-us"


[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  customCSS = ['css/custom.css']

  tags =  ['academic', 'personal', 'artistic']

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "projects/"
  url = "projects/"

  [[params.navlinks]]
  name = "quilts/"
  url = "projects/quilts/"

  [[params.navlinks]]
  name = "resume/"
  url = "/Meg_Anderson_Resume_20250728.pdf"

